// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANwjrLN2JiTK72F9dlN6-rB-9UCDLMG7Q',
    appId: '1:792884819574:web:50fda59c7d5ed824c21157',
    messagingSenderId: '792884819574',
    projectId: 'tanist-22f63',
    authDomain: 'tanist-22f63.firebaseapp.com',
    storageBucket: 'tanist-22f63.appspot.com',
    measurementId: 'G-1L21MNX9CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuOkrTfX9Dg0RmUQ9Q-Rfv7oQXqYKiyNE',
    appId: '1:792884819574:android:ce9b6dc88c561b5ac21157',
    messagingSenderId: '792884819574',
    projectId: 'tanist-22f63',
    storageBucket: 'tanist-22f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdlvWzNfRbY8bbvvOppobzAmnvH21rfE',
    appId: '1:792884819574:ios:bcf60c60bfc5f365c21157',
    messagingSenderId: '792884819574',
    projectId: 'tanist-22f63',
    storageBucket: 'tanist-22f63.appspot.com',
    iosBundleId: 'com.tanist.tanist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHdlvWzNfRbY8bbvvOppobzAmnvH21rfE',
    appId: '1:792884819574:ios:d954bfd34b3a7e24c21157',
    messagingSenderId: '792884819574',
    projectId: 'tanist-22f63',
    storageBucket: 'tanist-22f63.appspot.com',
    iosBundleId: 'com.tanist.tanist.RunnerTests',
  );
}
